### PR TITLE
Update for Laravel 5.4

### PR DESCRIPTION
**Pull request by JayBizzle**

### CODE REVIEW

**Review by Cherry-Pie — APPROVED** [review]
thanks!

**Comment by JayBizzle** [comment]
No worries.

FYI, this is compatible with all previous 5.* versions of Laravel

**Comment by JayBizzle** [comment]
@Cherry-Pie Could you tag a new release with these changes please.

Thanks 👍

**Comment by Cherry-Pie** [comment]
missed it, sry
done

**Comment by JayBizzle** [comment]
Cheers 👍

**Comment by JayBizzle** [comment]
Infact, sorry to be a pain, but packagist hasn't updated with the new version. Perhaps the webhook is broken.

https://packagist.org/packages/yaro/log-envelope

Can you force an update?

Thanks

**Comment by Cherry-Pie** [comment]
updated

**Comment by JayBizzle** [comment]
Thanks!

**Comment by JayBizzle** [comment]
Just realised, when you tagged a new release for this change, you inadvertently included the changes you made here 00794236b1b7c50b49aab6fc758d491a108960b9

This silently broke all logging for anyone that updated because then everyone needs to update their config file to the new config layout.

2 options:

1. Leave it as is and hope people figure it out.
2. Rollback all the changes back to `v1.2.0`, implement the Laravel 5.4 fix, then release `v1.2.2`. Then your breaking changes could go into a `v2.0.0` branch or a `v1.3.0` branch

**Comment by JayBizzle** [comment]
Any thoughts on this?

**Comment by ryross** [comment]
I'm still on Laravel 5.1 for one of my projects and this update definitely broke things for me. I agree with @JayBizzle that the breaking change should be moved to a v1.3.0 or v2.0.0 branch

**Comment by JayBizzle** [comment]
Any further thoughts on this? If you need any help sorting this, just give me a shout.

We are going to have to create a fork of this repo with the fixes in the meantime.

Thanks!

**Comment by Cherry-Pie** [comment]
Sorry for late response
I'll do it on this weekend

**Comment by JayBizzle** [comment]
I'll look forward to it, thanks!

**Comment by Cherry-Pie** [comment]
Old configuration version with L5.4 support is located under 1.2.2 tag, and new - 1.3.0.

**Comment by JayBizzle** [comment]
Brilliant, thanks.

Can confirm this is now working as expected 👍

**Pull request merged**
